config/routes.rb
Rails.application.routes.draw do
  root to: "tweets#index"
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  resources :tweets do
    resources :tweets
    post "like", on: :member
    delete "unlike", on: :member
  end
  namespace :api do
    resources :tweets, except: %i[new edit] do
      post "like", on: :member
      delete "unlike", on: :member
      get "/tweets", to: "tweets#replies", as: "show_replies"
    end
    resources :users, except: %i[new edit]
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    post "/test/tweets", to: "tweets#testcreate", as: "test_create"
    patch "/test/tweets/:tweet_id", to: "tweets#testupdate", as: "test_update"
    delete "/test/tweets", to: "tweets#testdestroy", as: "test_destroy"
  end
  get "/profiles/:user_id", to: "profiles#index", as: "profiles"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end
end

app/views/profiles/index.html.erb
<h2 class="title center-text">Profile</h2>


<div class="profile__data flex flex-column">
  <% if @user.avatar.attached? %>
    <%= image_tag(@user.avatar, class:"profile__data--icon") %>
  <% else %>
    <%= image_tag "image_profile_default.png", class:"profile__data--icon" %>
  <% end %>
  <div class="profile__data--main_text"><%= @user.name %></div>
  <div class="profile__data--sub_text"><%= @user.username %></div>
  <div class="profile__data--sub_text">Joined on <%= @user.created_at.strftime("%B %d, %Y") %></div>
  <% if @user.id == current_user.id %>
  <%= link_to "Edit Profile", edit_user_registration_path, class: "button button--primary  mb-4" %>
  <% end %>
</div>

<div class="profile__options mb-4">
  <div class="info-button made active">Tweets</div>
  <div class="info-button likes">Liked</div>
</div>

<div class="tweets-made active">
  <% @user.tweets.each do |tweet|%>
    <div class="tweet mb-2 full-width">
      <%= link_to tweet_path(tweet) do %>
        <%= link_to profiles_path(User.find(tweet.user_id).id) do %>
          <div class="tweet__header pointer">
            <% if @user.avatar.attached? %>
              <%= image_tag(@user.avatar, class:"tweet__header--icon") %>
            <% else %>
              <%= image_tag "image_profile_default.png", class:"tweet__header--icon" %>
            <% end %>
            <div class="tweet__header--data">
              <div class="flex">
                <p class="tweet__header--name">
                  <%=@user.name%>
                </p>
                <p class="tweet__header--user">
                  <%=@user.username%>
                </p>
              </div>
              <p class="tweet__header--time"><%=time_ago_in_words(tweet.updated_at)%> ago</p>
            </div>
          </div>
        <% end %>
        <div class="tweet__content">
          <%= link_to tweet_path(tweet.id) do %>
            <p class="mb-4 tweet__content--text">
              <%=tweet.body%>
            </p>
          <% end %>
        </div>
      <% end %>
      <div class="tweet__actions">
        <% if user_signed_in? && (tweet.user_id == current_user.id || current_user.role == "admin") %>
        <div class="flex">
          <div class="tweet__action--left ">
            <%= button_to tweet_path(tweet), method: :delete, "data-turbo": "false" ,class: "tweet__action--delete" do %>
              <%=image_tag "icons/delete.svg", class: "tweet__action--icon"%>
            <% end %>
          </div>
          <div class="tweet__action--left ">
            <%= link_to edit_tweet_path(tweet) do %>
              <%=image_tag "icons/edit.svg", class: "tweet__action--icon"%>
            <% end %>
          </div>
        </div>
        <% end %>
        <div class="flex">
          <div class="flex tweet__action--right">
            <%=image_tag "icons/msn.svg", class: "tweet__action--icon"%>
            <p><%=tweet.replies_count%> </p>
          </div>
          <div class="flex tweet__action--right ">
            <% if user_signed_in? && tweet.liked?(current_user) %>
              <%= button_to unlike_tweet_path(tweet), method: :delete, data: { turbo: "false" }, class: "flex tweet__action--delete" do %>
                <%=image_tag "icons/heart-active.svg", class: "tweet__action--icon"%>
              <% end %>
            <% else %>
              <%= button_to like_tweet_path(tweet), class: "flex tweet__action--delete" do %>
                <%=image_tag "icons/heart.svg", class: "tweet__action--icon"%>
              <% end %>
            <% end %>
            <%=tweet.likes_count%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="tweets-liked">
  <% @user.likes.each do |like| %>
    <% Tweet.where(id: like.tweet_id).each do |tweet| %>
    <% tweet_user = User.find(tweet.user_id)%>
    <div class="tweet mb-2 full-width">
      <%= link_to tweet_path(tweet) do %>
        <%= link_to profiles_path(User.find(tweet.user_id).id) do %>
          <div class="tweet__header pointer">
            <% if tweet_user.avatar.attached? %>
              <%= image_tag(tweet_user.avatar, class:"tweet__header--icon") %>
            <% else %>
              <%= image_tag "image_profile_default.png", class:"tweet__header--icon" %>
            <% end %>
            <div class="tweet__header--data">
              <div class="flex">
                <p class="tweet__header--name">
                  <%=tweet_user.name%>
                </p>
                <p class="tweet__header--user">
                  <%=tweet_user.username%>
                </p>
              </div>
              <p class="tweet__header--time"><%=time_ago_in_words(tweet.updated_at)%> ago</p>
            </div>
          </div>
        <% end %>
        <div class="tweet__content">
          <%= link_to tweet_path(tweet.id) do %>
            <p class="mb-4 tweet__content--text">
              <%=tweet.body%>
            </p>
          <% end %>
        </div>
      <% end %>
      <div class="tweet__actions">
        <% if user_signed_in? && (tweet.user_id == current_user.id || current_user.role == "admin") %>
        <div class="flex">
          <div class="tweet__action--left ">
            <%= button_to tweet_path(tweet), method: :delete, "data-turbo": "false" ,class: "tweet__action--delete" do %>
              <%=image_tag "icons/delete.svg", class: "tweet__action--icon"%>
            <% end %>
          </div>
          <div class="tweet__action--left ">
            <%= link_to edit_tweet_path(tweet) do %>
              <%=image_tag "icons/edit.svg", class: "tweet__action--icon"%>
            <% end %>
          </div>
        </div>
        <% end %>
        <div class="flex">
          <div class="flex tweet__action--right">
            <%=image_tag "icons/msn.svg", class: "tweet__action--icon"%>
            <p><%=tweet.replies_count%> </p>
          </div>
          <div class="flex tweet__action--right ">
            <% if user_signed_in? && tweet.liked?(current_user) %>
              <%= button_to unlike_tweet_path(tweet), method: :delete, data: { turbo: "false" }, class: "flex tweet__action--delete" do %>
                <%=image_tag "icons/heart-active.svg", class: "tweet__action--icon"%>
              <% end %>
            <% else %>
              <%= button_to like_tweet_path(tweet), class: "flex tweet__action--delete" do %>
                <%=image_tag "icons/heart.svg", class: "tweet__action--icon"%>
              <% end %>
            <% end %>
            <%=tweet.likes_count%>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>