config/routes.rb
Rails.application.routes.draw do
  root to: "tweets#index"
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  resources :tweets do
    resources :tweets
    post "like", on: :member
    delete "unlike", on: :member
  end
  namespace :api do
    resources :tweets, except: %i[new edit] do
      post "like", on: :member
      delete "unlike", on: :member
      get "/tweets", to: "tweets#replies", as: "show_replies"
    end
    resources :users, except: %i[new edit]
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    post "/test/tweets", to: "tweets#testcreate", as: "test_create"
    patch "/test/tweets/:tweet_id", to: "tweets#testupdate", as: "test_update"
    delete "/test/tweets", to: "tweets#testdestroy", as: "test_destroy"
  end
  get "/profiles/:user_id", to: "profiles#index", as: "profiles"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Validations
  validates :body, presence: true, length: { maximum: 140 }

  # Associations
  belongs_to :user

  belongs_to :parent, class_name: "Tweet",
                      optional: true,
                      counter_cache: :replies_count
  has_many :replies, class_name: "Tweet",
                     foreign_key: "parent_id",
                     dependent: :destroy,
                     inverse_of: "parent"
  has_many :likes, dependent: :destroy

  # Methods
  def liked?(user)
    !!self.likes.find { |like| like.user_id == user.id }
  end
end

app/controllers/api/tweets_controller.rb
module Api
  class TweetsController < Api::ApiController
    before_action :set_tweet, only: %i[show update destroy like unlike]

    def index
      @tweets = Tweet.all
      render json: @tweets, status: :ok
    end

    def show
      # @tweet = Tweet.find(params[:id])
      render json: @tweet, status: :ok
    end

    def create
      @tweet = Tweet.new(tweet_params)
      @tweet.user_id = current_user.id
      @tweet.parent_id = params["parent_id"] if params["parent_id"]
      
      if @tweet.save
        render json: @tweet, status: :created
      else
        render json: { errors: @tweet.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def update
      # @tweet = Tweet.find(params[:id])
      authorize(@tweet)
      if @tweet.update(tweet_params)
        render json: @tweet, status: :ok
      else
        render json: { errors: @tweet.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def destroy
      # tweet = Tweet.find(params[:id])
      authorize(@tweet)
      @tweet.destroy
      head :no_content
      
    end

    # Custom methods
    def like
      like = Like.new(user_id: current_user.id, tweet_id: @tweet.id)
      # redirect_to root_path if like.save
      redirect_to root_path if like.save
    end

    def unlike
      like_to_destroy = Like.find_by(user_id: current_user.id, tweet_id: @tweet.id)
      redirect_to root_path if like_to_destroy.destroy
    end

    def replies
      @parent = Tweet.find(params["tweet_id"])
      render json: @parent.replies, status: :ok
    end

    def testcreate
      @tweet = Tweet.new(tweet_params)
      @tweet.user_id = User.all.first.id
      @tweet.parent_id = params["parent_id"] if params["parent_id"]
      
      if @tweet.save
        render json: @tweet, status: :created
      else
        render json: { errors: @tweet.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def testupdate
      @tweet = Tweet.find(params[:id])
      
      if @tweet.update(tweet_params)
        render json: @tweet, status: :ok
      else
        render json: { errors: @tweet.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def testdestroy
      @tweet = Tweet.find(params[:id])
      @tweet.destroy
      head :no_content
    end

    private

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy like unlike]

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def show
    # @tweet = Tweet.find(params[:id])
    @new_tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params) 
    if params["tweet_id"]
      @reply = @tweet
      @reply.user = current_user
      @parent_tweet = Tweet.find(params["tweet_id"])
      @reply.parent_id = @parent_tweet.id
      if @reply.save
        redirect_to tweet_path(params["tweet_id"]), notice: "Reply created"
      else
        render tweet_path(params["tweet_id"]), notice: "Reply could not be created", status: :unprocessable_entity
      end
    else
      @tweet.user = current_user
      if @tweet.save
        redirect_to root_path, notice: "Tweet created", status: :created
      else
        render root_path, notice: "Tweet could not be created", status: :unprocessable_entity
      end
    end
  end

  def edit
    # @tweet = Tweet.find(params[:id])
    authorize(@tweet)
    @parent_tweet = Tweet.find(params["tweet_id"]) if params["tweet_id"]
  end

  def update
    # @tweet = Tweet.find(params[:id])
    authorize(@tweet)
    if params["tweet_id"]
      if @tweet.update(tweet_params)
        redirect_to tweet_path(params["tweet_id"]), notice: "Tweet successfully updated"
      else
        render :edit, notice: "Tweet could not be updated", status: :unprocessable_entity
      end
    elsif !params["tweet_id"]
      if @tweet.update(tweet_params)
        redirect_to root_path, notice: "Tweet successfully updated"
      else
        render :edit, notice: "Tweet could not be updated", status: :unprocessable_entity
      end
    end
  end

  def destroy
    # tweet = Tweet.find(params[:id])
    authorize(@tweet)
    @tweet.destroy

    if params["tweet_id"]
      redirect_to tweet_path(params["tweet_id"]), notice: "Tweet deleted", status: :see_other
    else
      redirect_to root_path, notice: "Tweet deleted", status: :see_other
    end
  end

  # Custom methods

  def like
    like = Like.new(user_id: current_user.id, tweet_id: @tweet.id)
    # redirect_to root_path if like.save
    if @tweet.parent_id
      redirect_to tweet_path(@tweet.parent_id) if like.save
    else
      redirect_to root_path if like.save
    end
    
  end

  def unlike
    like_to_destroy = Like.find_by(user_id: current_user.id, tweet_id: @tweet.id)

    if @tweet.parent_id
      redirect_to tweet_path(@tweet.parent_id) if like_to_destroy.destroy
    else
      redirect_to root_path if like_to_destroy.destroy
    end

  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, method: :post, class:"form__tweet") do |f| %> <%=
error_for(tweet, :body) %>
<div class="field mb-4">
  <div class="input__container form__tweet--container">
    <%= f.text_area :body, placeholder: "Remember to thing before write...",
    autofocus: true , class: "input__content form__tweet--area"%>
      <%= f.submit "TWEET",class: "button button--primary" %>
  </div>
</div>

<% end %>

app/views/tweets/edit.html.erb
<h2 class="title center-text">Edit Tweet</h2>


<% if @parent_tweet%> 
  <%= form_with(model: [@parent_tweet, @tweet], method: :patch, class:"form__tweet full-width") do |f| %>
    <%= error_for(@tweet, :body) %>
    <div class="field mb-4">
      <div class="input__container form__tweet--container">
        <%= f.text_area :body, placeholder: "Edit your tweet here...",
        autofocus: true , class: "input__content form__tweet--area"%>
          <%= f.submit "Update",class: "button button--primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <%= form_with(model: @tweet, method: :patch, class:"form__tweet full-width") do |f| %>
    <%= error_for(@tweet, :body) %>
    <div class="field mb-4">
      <div class="input__container form__tweet--container">
        <%= f.text_area :body, placeholder: "Edit your tweet here...",
        autofocus: true , class: "input__content form__tweet--area"%>
          <%= f.submit "Update",class: "button button--primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tweets/index.html.erb
<section class="tweets">
  <h1 class="title mb4">Home</h1>
  <% if user_signed_in? %>
  <%= render "form", tweet: @tweet %>
  <% end %>
  <%@tweets.each do |tweet|%>
    <% if tweet.parent_id == nil%>
      <div class="tweet mb-2">
        <%= link_to profiles_path(User.find(tweet.user_id).id) do %>
          <div class="tweet__header">
            <% if User.find(tweet.user_id).avatar.attached? %>
            
                <%= image_tag(User.find(tweet.user_id).avatar, class:"tweet__header--icon pointer")  %>
              
            <% else %>
              <%= link_to profiles_path(User.find(tweet.user_id).id) do %>
                <%= image_tag "image_profile_default.png", class:"tweet__header--icon pointer"  %>
              <% end %>
            <% end %>
            <div class="tweet__header--data">
              <div class="flex">
                <p class="tweet__header--name">
                  <%=User.find(tweet.user_id).name%>
                </p>
                <p class="tweet__header--user">
                  <%=User.find(tweet.user_id).username%>
                </p>
              </div>
              <p class="tweet__header--time"><%=time_ago_in_words(tweet.updated_at)%> ago</p>
            </div>
          </div>
          <% end %>
          <div class="tweet__content">
          <%= link_to tweet_path(tweet.id) do %>
            <p class="mb-4 tweet__content--text">
              <%=tweet.body%>
            </p>
          <% end %>
          </div>
        <div class="tweet__actions">
          <% if user_signed_in? && (tweet.user_id == current_user.id || current_user.role == "admin") %>
          <div class="flex">
            <div class="tweet__action--left ">
              <%= button_to tweet_path(tweet), method: :delete, "data-turbo": "false" ,class: "tweet__action--delete" do %>
                <%=image_tag "icons/delete.svg", class: "tweet__action--icon"%>
              <% end %>
            </div>
            <div class="tweet__action--left ">
              <%= link_to edit_tweet_path(tweet) do %>
                <%=image_tag "icons/edit.svg", class: "tweet__action--icon"%>
              <% end %>
            </div>
          </div>
          <% end%>
          <div class="flex">
            <div class="flex tweet__action--right">
              <%= link_to tweet_path(tweet)do %>
                <%=image_tag "icons/msn.svg", class: "tweet__action--icon"%>
              <% end %>
              <p><%=tweet.replies_count%> </p>
            </div>
            <div class="flex tweet__action--right ">
              <% if user_signed_in? && tweet.liked?(current_user) %>
                <%= button_to unlike_tweet_path(tweet), method: :delete, data: { turbo: "false" }, class: "flex tweet__action--delete" do %>
                  <%=image_tag "icons/heart-active.svg", class: "tweet__action--icon"%>
                <% end %>
              <% else %>
                <%= button_to like_tweet_path(tweet), class: "flex tweet__action--delete" do %>
                  <%=image_tag "icons/heart.svg", class: "tweet__action--icon"%>
                <% end %>
              <% end %>
              <%=tweet.likes_count%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/tweets/new.html.erb
<%= render "form", tweet: @tweet %>

app/views/tweets/show.html.erb
<section class="tweets">
  <h2 class="title">Tweet Detail</h2>
  <div  class="tweet mb-4">
    <div class="tweet__header">
      <% if User.find(@tweet.user_id).avatar.attached? %>
        <%= image_tag(User.find(@tweet.user_id).avatar, class:"tweet__header--icon") %>
      <% else %>
        <%= image_tag "image_profile_default.png", class:"tweet__header--icon pointer"  %>
      <% end %>
      <div class="tweet__header--data">
        <div class="flex">
          <p class="tweet__header--name">
            <%=User.find(@tweet.user_id).name%>
          </p>
          <p class="tweet__header--user">
            <%=User.find(@tweet.user_id).username%>
          </p>
        </div>
        <p class="tweet__header--time"><%=time_ago_in_words(@tweet.updated_at)%> ago</p>
      </div>
    </div>
    <div class="tweet__content">
      <p class="mb-4 tweet__content--text">
        <%=@tweet.body%>
      </p>
    </div>
    <div class="tweet__actions">
      <% if user_signed_in? && (@tweet.user_id == current_user.id || current_user.role == "admin") %>
      <div class="flex">
        <div class="tweet__action--left ">
          <%= button_to tweet_path(@tweet), method: :delete, "data-turbo": "false" ,class: "tweet__action--delete" do %>
            <%=image_tag "icons/delete.svg", class: "tweet__action--icon"%>
          <% end %>
        </div>
        <div class="tweet__action--left ">
          <%= link_to edit_tweet_path(@tweet) do %>
            <%=image_tag "icons/edit.svg", class: "tweet__action--icon"%>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="flex">
        <div class="flex tweet__action--right">
          <%=image_tag "icons/msn.svg", class: "footer__students--icon"%>
          <p><%=@tweet.replies_count%> </p>
        </div>
        <div class="flex tweet__action--right ">
          <% if user_signed_in? && @tweet.liked?(current_user) %>
            <%= button_to unlike_tweet_path(@tweet), method: :delete, data: { turbo: "false" }, class: "flex tweet__action--delete" do %>
              <%=image_tag "icons/heart-active.svg", class: "footer__students--icon"%>
            <% end %>
          <% elsif user_signed_in? && !@tweet.liked?(current_user) %>
            <%= button_to like_tweet_path(@tweet), class: "flex tweet__action--delete" do %>
              <%=image_tag "icons/heart.svg", class: "footer__students--icon"%>
            <% end %>
          <% end %>
          <%=@tweet.likes_count%>
        </div>
      </div>
    </div>
  </div>
  <div class=".gray-line mb-4">
  </div>
  <%if user_signed_in? %>
    <%= form_with(model: [@tweet, @new_tweet], method: :post ,class:"form__tweet") do |f| %>
      <%= error_for(@tweet, :body) %>
      <div class="field mb-6">
        <div class="input__container form__tweet--container">
          <%= f.text_area :body, placeholder: "Something to say about it?", autofocus: true, class: "input__content form__tweet--area"%>
          <%= f.submit "TWEET",class: "button button--primary" %>
        </div>
      </div>
    <% end %>
  <% end %>
  
  <% @tweet.replies.each do |reply| %>
    <div class="tweet mb-2">
      <%= link_to profiles_path(User.find(reply.user_id).id) do %>
        <div class="tweet__header pointer">
          <% if User.find(reply.user_id).avatar.attached? %>
            <%= image_tag(User.find(reply.user_id).avatar, class:"tweet__header--icon") %>
          <% else %>
            <%= image_tag "image_profile_default.png", class:"tweet__header--icon" %>
          <% end %>
          <div class="tweet__header--data">
            <div class="flex">
              <p class="tweet__header--name">
                <%=User.find(reply.user_id).name%>
              </p>
              <p class="tweet__header--user">
                <%=User.find(reply.user_id).username%>
              </p>
            </div>
            <p class="tweet__header--time"><%=time_ago_in_words(reply.updated_at)%> ago</p>
          </div>
        </div>
      <% end %>
      <div class="tweet__content">
        <%= link_to tweet_path(reply.id) do %>
          <p class="mb-4 tweet__content--text pointer">
            <%=reply.body%>
          </p>
        <% end %>
      </div>
      <div class="tweet__actions">
        <% if user_signed_in? && (reply.user_id == current_user.id || current_user.role == "admin") %>
          <div class="flex">
            <div class="tweet__action--left ">
              <%= button_to tweet_tweet_path(@tweet, reply), method: :delete, "data-turbo": "false", "data-turbo": "false" ,class: "tweet__action--delete" do %>
                <%=image_tag "icons/delete.svg", class: "tweet__action--icon"%>
              <% end %>
            </div>
            <div class="tweet__action--left ">
              <%= link_to edit_tweet_tweet_path(@tweet, reply) do %>
                <%=image_tag "icons/edit.svg", class: "tweet__action--icon"%>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="flex">
          <div class="flex tweet__action--right">
            <%=image_tag "icons/msn.svg", class: "footer__students--icon"%>
            <p><%=reply.replies_count%> </p>
          </div>
          <div class="flex tweet__action--right">
          <% if user_signed_in? && reply.liked?(current_user) %>
                <%= button_to unlike_tweet_path(reply), method: :delete, data: { turbo: "false" }, class: "flex tweet__action--delete" do %>
                  <%=image_tag "icons/heart-active.svg", class: "tweet__action--icon"%>
                <% end %>
              <% else %>
                <%= button_to like_tweet_path(reply), class: "flex tweet__action--delete" do %>
                  <%=image_tag "icons/heart.svg", class: "tweet__action--icon"%>
                <% end %>
              <% end %>
            <%=reply.likes_count%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>